version: "3.9"

services:

  catalog-service:
    image: service-domain/catalog-service:1.0.0
    container_name: catalog-service
    env_file:
      - .env
    ports:
      - "8084:8084"
    depends_on:
      - mongo
      - redis
    networks:
      - user-network

  mongo:
    image: mongo:latest
    container_name: mongodb_catalog
    ports:
      - "27017:27017"
    networks:
      - user-network

  redis:
    image: redis:7
    container_name: redis_catalog
    ports:
      - "6379:6379"
    networks:
      - user-network

networks:
  user-network:
    external: true
