# --- ETAPA 1: Construcción (Builder) ---
FROM python:3.10-slim AS builder

WORKDIR /app
RUN apt-get update && apt-get install -y --no-install-recommends \
    gcc \
    libpq-dev \
    python3-dev \
    && rm -rf /var/lib/apt/lists/*

COPY requirements.txt .
RUN pip install --user --no-cache-dir -r requirements.txt

# --- ETAPA 2: Imagen Final ---
FROM python:3.10-slim

# PYTHONUNBUFFERED=1 permite ver los logs en tiempo real (Punto 17)
ENV PYTHONUNBUFFERED=1 
WORKDIR /app

RUN apt-get update && apt-get install -y --no-install-recommends \
    libpq-dev \
    && rm -rf /var/lib/apt/lists/*

COPY --from=builder /root/.local /root/.local
COPY . .

ENV PATH=/root/.local/bin:$PATH

EXPOSE 8082

# Ejecutamos con log-level info para ver todo lo que pasa
CMD ["uvicorn", "app.main:app", "--host", "0.0.0.0", "--port", "8082", "--log-level", "info"]
