version: "3.9"

services:
  user-authentication-service:
    image: dayanaheredia/user-authentication-service:latest
    build:
      context: .
      dockerfile: docker/Dockerfile
    container_name: user-authentication-service
    restart: unless-stopped
    env_file:
      - .env
    ports:
      - "8082:8082"
    networks:
      - user-network

networks:
  user-network:
    external: true
