version: "3.9"

services:
  scheduling-management-service:
    image: dayanaheredia/scheduling-management-service:latest
    build:
      context: .
      dockerfile: docker/Dockerfile
    container_name: scheduling-management-service
    ports:
      - "8085:8085"
    env_file:
      - .env
    networks:
      - user-network
    restart: always

networks:
  user-network:
    external: true
