services:
  user-profile-service:
    image: dayanaheredia/user-profile-service:latest
    build:
      context: .
      dockerfile: docker/Dockerfile
    container_name: user-profile-service
    env_file:
      - .env
    ports:
      - "8083:8083"
    networks:
      - user-network

networks:
  user-network:
    external: true
