services:

  # ==========================
  # POSTGRES – APPOINTMENTS DB
  # ==========================
  db-appointments:
    image: postgres:15
    container_name: db-appointments
    environment:
      POSTGRES_USER: appointment_user
      POSTGRES_PASSWORD: appointment_pass
      POSTGRES_DB: appointments_db
    ports:
      - "5434:5432"
    volumes:
      - appointments_db_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U appointment_user -d appointments_db"]
      interval: 5s
      timeout: 5s
      retries: 5
    networks:
      - user-network

  # ==========================
  # MQTT – HiveMQ
  # ==========================
  hivemq:
    image: hivemq/hivemq4:4.20.0
    container_name: hivemq
    ports:
      - "1883:1883"
      - "8080:8080"
    networks:
      - user-network

  # ==========================
  # APPOINTMENT CREATION SERVICE
  # ==========================
  appointment-creation-service:
    container_name: appointment-creation-service
    build:
      context: .
      dockerfile: docker/Dockerfile
    image: dayanaheredia/appointment-creation-service:latest
    env_file:
      - .env
    ports:
      - "8087:8087"
    depends_on:
      - db-appointments
      - hivemq
    networks:
      - user-network

# ==========================
# VOLUMES
# ==========================
volumes:
  appointments_db_data:

# ==========================
# NETWORK
# ==========================
networks:
  user-network:
    external: true
