name: User Domain - User Registration Service CI/CD

on:
  push:
    branches:
      - QA
      - main
    paths:
      - Backend/User-Domain/user-registration-service/**
      - Terraform/labs/user-domain/user-registration/**
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: Backend/User-Domain/user-registration-service

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.10"

      - name: Install dependencies
        run: |
          pip install --upgrade pip
          pip install -r requirements.txt
          pip install pytest

      - name: Run tests
        run: pytest -v
